[package]
name = "rpsx-emu"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "*" }
wgpu = "*"
anyhow = "*"
vek = "*"
bytemuck = {version = "*", features = [ "derive" ] }
cgmath = "0.18"
pollster = "*"
web-time = "*"
env_logger = "*"
log = "*"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]
